/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CarrierService } from "../carrier.service";
import { CarrierCreateInput } from "./CarrierCreateInput";
import { Carrier } from "./Carrier";
import { CarrierFindManyArgs } from "./CarrierFindManyArgs";
import { CarrierWhereUniqueInput } from "./CarrierWhereUniqueInput";
import { CarrierUpdateInput } from "./CarrierUpdateInput";

export class CarrierControllerBase {
  constructor(protected readonly service: CarrierService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Carrier })
  async createCarrier(
    @common.Body() data: CarrierCreateInput
  ): Promise<Carrier> {
    return await this.service.createCarrier({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Carrier] })
  @ApiNestedQuery(CarrierFindManyArgs)
  async carriers(@common.Req() request: Request): Promise<Carrier[]> {
    const args = plainToClass(CarrierFindManyArgs, request.query);
    return this.service.carriers({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Carrier })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async carrier(
    @common.Param() params: CarrierWhereUniqueInput
  ): Promise<Carrier | null> {
    const result = await this.service.carrier({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Carrier })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCarrier(
    @common.Param() params: CarrierWhereUniqueInput,
    @common.Body() data: CarrierUpdateInput
  ): Promise<Carrier | null> {
    try {
      return await this.service.updateCarrier({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Carrier })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCarrier(
    @common.Param() params: CarrierWhereUniqueInput
  ): Promise<Carrier | null> {
    try {
      return await this.service.deleteCarrier({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
